blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Github Discussions
    url: https://github.com/Milkdown/milkdown/discussions
    about: Use github issues for bug reports and feature requests. For questions please use discussions.
  - name: ğŸ™ Discord Community
    url: https://discord.gg/SdMnrSMyBX
    about: Ask for help in the Discord community.
